CREATE TABLE `PAIS` (
  `ID_PAIS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PAIS` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID_PAIS`)
);

CREATE TABLE `PROVINCIA` (
  `ID_PROVINCIA` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROVINCIA` VARCHAR(40) NOT NULL,
  `ID_PAIS` INT NOT NULL,
  PRIMARY KEY (`ID_PROVINCIA`),
  FOREIGN KEY (`ID_PAIS`) REFERENCES `PAIS`(`ID_PAIS`)
);

CREATE TABLE `CIUDAD` (
  `ID_CIUDAD` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_CIUDAD` VARCHAR(40) NOT NULL,
  `ID_PROVINCIA` INT NOT NULL,
  PRIMARY KEY (`ID_CIUDAD`),
  FOREIGN KEY (`ID_PROVINCIA`) REFERENCES `PROVINCIA`(`ID_PROVINCIA`)
);

CREATE TABLE `SUCURSAL` (
  `ID_SUCURSAL` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_SUCURSAL` VARCHAR(40) NOT NULL,
  `ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_SUCURSAL`),
  FOREIGN KEY (`ID_CIUDAD`) REFERENCES `CIUDAD`(`ID_CIUDAD`)
);

CREATE TABLE `SEXO` (
  `ID_SEXO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION_SEXO` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_SEXO`)
);

CREATE TABLE `PERSONA` (
  `ID_PERSONA` INT NOT NULL AUTO_INCREMENT,
  `IDENTIFICACION` VARCHAR(20) NOT NULL UNIQUE,
  `NOMBRE` VARCHAR(30) NOT NULL,
  `APELLIDOS` VARCHAR(30) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `DIRECCION_RESIDENCIA` VARCHAR(20) NOT NULL,
  `ID_SEXO` INT NOT NULL,
  `ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_PERSONA`),
  FOREIGN KEY (`ID_SEXO`) REFERENCES `SEXO`(`ID_SEXO`),
  FOREIGN KEY (`ID_CIUDAD`) REFERENCES `CIUDAD`(`ID_CIUDAD`)
);

CREATE TABLE `PUESTO_LABORAL` (
  `ID_PUESTO_LABORAL ` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(30) NOT NULL,
  `SALARIO_MENSUAL` FLOAT DEFAULT 0.0,
  PRIMARY KEY (`ID_PUESTO_LABORAL `)
);

CREATE TABLE `EMPLEADO` (
  `ID_EMPLEADO` INT NOT NULL AUTO_INCREMENT,
  `FECHA_CONTRATADO` DATE NOT NULL,
  `HORAS_LABORALES` INT DEFAULT 0,
  `ID_SUCURSAL` INT NOT NULL,
  `ID_PUESTO_LABORAL` INT NOT NULL,
  `ID_PERSONA` INT NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  FOREIGN KEY (`ID_PUESTO_LABORAL`) REFERENCES `PUESTO_LABORAL`(`ID_PUESTO_LABORAL `),
  FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`),
  FOREIGN KEY (`ID_SUCURSAL`) REFERENCES `SUCURSAL`(`ID_SUCURSAL`)
);

CREATE TABLE `TIPO_USUARIO` (
  `ID_TIPO_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_TIPO_USUARIO`)
);

CREATE TABLE `USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_USUARIO` VARCHAR(20) NOT NULL,
  `CONTRASEÑA` VARCHAR(20) NOT NULL,
  `ID_TIPO_USUARIO` INT NOT NULL,
  `ID_PERSONA` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  FOREIGN KEY (`ID_TIPO_USUARIO`) REFERENCES `TIPO_USUARIO`(`ID_TIPO_USUARIO`),
  FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`)
);

CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO`(`ID_USUARIO`)
);

CREATE TABLE `PROVEEDOR` (
  `ID_PROVEEDOR` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROVEEDOR` VARCHAR(50) NOT NULL,
  `PORCENTAJE_G` FLOAT NOT NULL,
  `ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_PROVEEDOR`),
  FOREIGN KEY (`ID_CIUDAD`) REFERENCES `CIUDAD`(`ID_CIUDAD`)
);

CREATE TABLE `IMPUESTO` (
  `ID_IMPUESTO` INT NOT NULL AUTO_INCREMENT,
  `PORCENTAJE` FLOAT NOT NULL,
  `DESCRIPCION` VARCHAR(20) NOT NULL,
  KEY `ID` (`ID_IMPUESTO`)
);

CREATE TABLE `TIPO_PRODUCTO` (
  `ID_TIPO_PRODUCTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_TIPO_PRODUCTO` VARCHAR(50) NOT NULL,
  `DESCRIPCION_T_PRODU` VARCHAR(30) NOT NULL,
  `ID_IMPUESTO` INT NOT NULL,
  PRIMARY KEY (`ID_TIPO_PRODUCTO`),
  FOREIGN KEY (`ID_IMPUESTO`) REFERENCES `IMPUESTO`(`ID_IMPUESTO`)
);

CREATE TABLE `FACTURA` (
  `ID_FACTURA` INT NOT NULL AUTO_INCREMENT,
  `FECHA_FACTURA` DATE NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  `ID_EMPLEADO` INT NOT NULL,
  PRIMARY KEY (`ID_FACTURA`),
  FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE`(`ID_CLIENTE`),
  FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `EMPLEADO`(`ID_EMPLEADO`)
);

CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PRODUTO` VARCHAR(50) NOT NULL,
  `FECHA_PRODUCCION` DATE NOT NULL,
  `FECHA_VENCIMIENTO` DATE NOT NULL,
  `PRECIO_VENTA` FLOAT DEFAULT 0.0,
  `ID_TIPO_PRODUCTO` INT NOT NULL,
  `CANT_MINIMA` INT DEFAULT 0 ,
  `CANT_MAXIMA` INT DEFAULT 0,
  PRIMARY KEY (`ID_PRODUCTO`),
  FOREIGN KEY (`ID_TIPO_PRODUCTO`) REFERENCES `TIPO_PRODUCTO`(`ID_TIPO_PRODUCTO`)
);

CREATE TABLE `FACTURA_PRODUCTO` (
  `ID_FACTURA` INT NOT NULL,
  `ID_PRODUCTO` INT NOT NULL,
  `CANT_PRODU` INT NOT NULL,
  FOREIGN KEY (`ID_FACTURA`) REFERENCES `FACTURA`(`ID_FACTURA`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(`ID_PRODUCTO`)
);

CREATE TABLE `TELEF_PERSO` (
  `ID_PERSONA` INT NOT NULL,
  `NUM_TELEF` VARCHAR(15) NOT NULL,
  FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`)
);

CREATE TABLE `BODEGA` (
  `ID_BODEGA` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUCTO` INT NOT NULL,
  `ID_SUCURSAL` INT NOT NULL,
  `PRECIO_COMPRA` FLOAT NOT NULL,
  `ID_PROVEEDOR` INT NOT NULL,
  `FECHA_COMPRA` DATE NOT NULL,
  `CANTIDAD_ACTUAL` INT NOT NULL,
  PRIMARY KEY (`ID_BODEGA`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(`ID_PRODUCTO`),
  FOREIGN KEY (`ID_SUCURSAL`) REFERENCES `SUCURSAL`(`ID_SUCURSAL`),
  FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `PROVEEDOR`(`ID_PROVEEDOR`)
);

CREATE TABLE `CRIPTOCARTERA` (
  `ID_CRIPTOCARTERA` INT NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` INT NOT NULL,
  `NUM_CARTERAC` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_CRIPTOCARTERA`),
  FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE`(`ID_CLIENTE`)
);

CREATE TABLE `TARJETA_CREDITO` (
  `ID_TARJETA_CREDITO` INT NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` INT NOT NULL,
  `NUM_TARJETA_CREDITO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_TARJETA_CREDITO`),
  FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE`(`ID_CLIENTE`)
);

CREATE TABLE `CHEQUE` (
  `ID_CHEQUE` INT NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` INT NOT NULL,
  `NUM_CHEQUE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_CHEQUE`),
  FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE`(`ID_CLIENTE`)
);

