/* CANTIDAD DE DIAS QUE HACEN FALTA PARA QUE CADUQUE UN PRODUCTO */
CREATE PROCEDURE DIAS_CADUCIDAD_PRODUCTO (ID_PRODUCTO INT)
BEGIN
	DECLARE @CADUCIDAD_DIAS INT,
    DECLARE @FECHA_ACTUAL DATE = CAST(GETDATE() AS DATE)
    
    /* Devuelve el número de días entre dos valores de fecha */
    SELECT @CADUCIDAD_DIAS = DATEDIFF(DAY, @FECHA_ACTUAL, PRODUCTO.FECHA_VENCIMIENTO)
    FROM PRODUCTO
    WHERE @ID_PRODUCTO = PRODUCTO.ID_PRODUCTO
    
    IF (@CADUCIDAD_DIAS < 0) 
    BEGIN
		SET @CADUCIDAD_DIAS = 0
	END
	RETURN @CADUCIDAD_DIAS
END

/* CANTIDAD DE TIEMPO QUE LLEVA TRABAJANDO UN EMPLEADO */
CREATE PROCEDURE TIEMPO_LABORAL_EMPLEADO (ID_EMPLEADO INT)
BEGIN
	DECLARE @FECHA_CONTRATACION DATE
    DECLARE @FECHA_ACTUAL DATE = CAST(GETDATE() AS DATE)
    
	SELECT 
		@FECHA_CONTRATACION = EMPLEADO.FECHA_CONTRATACION
    FROM 
		EMPLEADO
    WHERE 
		@ID_EMPLEADO = EMPLEADO.ID_EMPLEADO
    
    DECLARE @DIAS INT = DATEDIFF(DAY, @FECHA_CONTRATACION, @FECHA_ACTUAL)
    RETURN @DIAS
END

/* CANTIDAD DE FACTURAS QUE REALIZA UN EMPLEADO */
CREATE PROCEDURE CANTIDAD_FACTURAS_EMPLEADO (ID_EMPLEADO INT)
BEGIN
	DECLARE @CANTIDAD_FACTURAS INT
    
    SELECT
		@CANTIDAD_FACTURAS = COUNT(FACTURA.ID_FACTURA)
	FROM 
		FACTURA
	WHERE
		@ID_EMPLEADO = FACTURA.ID_EMPLEADO
	
    RETURN @CANTIDAD_FACTURAS
END

/* CANTIDAD DE EMPLEADOS DE UNA SUCURSAL */
CREATE PROCEDURE EMPLEADOS_SUCURSAL (ID_SUCURSAL INT)
BEGIN
	DECLARE @CANTIDAD_EMPLEADOS INT
    
	SELECT 
		@CANTIDAD_EMPLEADOS = COUNT(EMPLEADO.ID_EMPLEADO)
	FROM 
		EMPLEADO
	INNER JOIN
		SUCURSAL
	ON
		EMPLEADO.ID_SUCURSAL_EMPLEADO = SUCURSAL.ID_SUCURSAL	
	WHERE 
		@ID_SUCURSAL = SUCURSAL.ID_SUCURSAL

	RETURN @CANTIDAD_EMPLEADOS
END

/* CANTIDAD DE PRODUCTOS EN UNA SUCURSAL */
CREATE PROCEDURE PRODUCTOS_SUCURSAL (ID_SUCURSAL INT)
BEGIN
	DECLARE @CANTIDAD_PRODUCTOS INT
    
    SELECT
		@CANTIDAD_PRODUCTOS = SUM(PRODUCTO.CANTIDAD_PRODUCTO)
	FROM
		PRODUCTO
	WHERE
		@ID_SUCURSAL = PRODUCTO.ID_SUCURSAL
	
    RETURN @CANTIDAD_PRODUCTOS
END
/* CANTIDAD DE SUCURSALES EN UN PAIS */
CREATE PROCEDURE SUCURSALES_PAIS (ID_PAIS INT)
BEGIN
	DECLARE @CANTIDAD_SUCURSALES INT
    
    SELECT
		@CANTIDAD_SUCURSALES = COUNT(SUCURSAL.ID_SUCURSAL)
	FROM
		SUCURSAL
	INNER JOIN
		CIUDAD
	ON
		SUCURSAL.ID_CIUDAD = CIUDAD.ID_CIUDAD
	INNER JOIN
		DEPARTAMENTO
	ON
		CIUDAD.ID_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO
	INNER JOIN
		PAIS
	ON
		DEPARTAMENTO.ID_PAIS = PAIS.ID_PAIS
	
    WHERE
		@ID_PAIS = PAIS.ID_PAIS
	
    RETURN @CANTIDAD_SUCURSALES
    
END

/* DINERO FACTURADO EN UNA FECHA */
CREATE PROCEDURE VENDIDO_FECHA (FECHA DATE, ID_SUCURSAL)
BEGIN
	DECLARE @DINERO_FACTURADO FLOAT = 0
    
    SELECT 
		@DINERO_FACTURADO = @DINERO_FACTURADO + FACTURA_PRODUCTO.CANTIDAD_PRODUCTO * PRODUCTO.VENTA_PRODUCTO
	FROM FACTURA_PRODUCTO
	INNER JOIN
		PRODUCTO
	ON
		FACTURA_PRODUCTO.ID_PRODUCTO = PRODUCTO.ID_PRODUCTO
	INNER JOIN
		FACTURA
	ON
		FACTURA_PRODUCTO.ID_FACTURA = FACTURA.ID_FACTURA
	WHERE
		@FECHA = FACTURA.FECHA_FACTURA AND @ID_SUCURSAL = FACTURA.ID_SUCURSAL
	
    RETURN @DINERO_FACTURADO
END